language: clojure
branches:
  except:
    - gh-pages
before_deploy:
  - lein codox
deploy:
  - provider: script
    cleanup: false
    script: lein deploy
    on:
      branch: master
  - provider: pages
    cleanup: false
    keep_history: true
    token: $GITHUB_TOKEN
    local_dir: codox
    on:
      branch: master
